import hashlib


def hexToBin(hexString):
    """takes a hex string, converts it to a binary string, trims the '0b'
    prefix, and pads it with leading zeroes to ensure a 256 bit length"""
    binaryString = bin(int(hexString, 16))[2:]
    if len(binaryString) < 256:
        prefix = "0" * (256 - len(binaryString))
        binaryString = prefix + binaryString
    return binaryString


def hashEncode(string):
    """Helper function to encode and hash string and return a hex string"""
    return hashlib.sha3_256(string.encode()).hexdigest()


def verifySignature(messageHash, signatureArray, pubKey):
    """Takes three args: message, signature as generated by signMessage, and a
    public key, returns True/False as to whether signature is valid for public
    key"""
    binString = hexToBin(messageHash)
    hashOfSig = []
    verificationArray = []
    for i in range(len(signatureArray)):
        hashOfSig.append(hashEncode(signatureArray[i]))
    for i in range(len(binString)):
        bit = int(binString[i])
        verificationArray.append(pubKey[i][bit])
    if verificationArray == hashOfSig:
        return True
    else:
        return False
